import { useEffect, useMemo, useRef, useState } from 'react';
import { listen } from '@tauri-apps/api/event';
import { invoke } from '@tauri-apps/api/core';
import { getCurrentWebview } from '@tauri-apps/api/webview';
import { cancelDocumentTranslation, chooseDocument, getDocumentResultPreview, inspectDocumentPath, translateDocument } from './documentApi';
import { DocumentOptions } from './DocumentOptions';
import { DocumentReport } from './DocumentReport';
import type { ChosenDocument, DocumentJobEvent, DocumentOptions as Options, DocumentProgress, DocumentReport as Report, DocumentResultPreview, PreparedDocumentRecovery } from './types';
import type { AppSettings } from '../settings/SettingsView';
import { SecretModeSwitch,useSecretMode } from '../history/secretMode';

const defaults: Options = { includeComments: true, includeNotes: true, includeHidden: false, wrapText: true, targetLanguage: 'ko', sourceLanguage: null, profileId: null, model: null, quality: null, pdfForceOcr: false, pdfFit: true, preserveAnnotations: true, secret: false, outputDirectory: null };
const stages: Record<string, { ko: string; en: string }> = { inspect: { ko: '문서 검사', en: 'Inspecting' }, extract: { ko: '텍스트 추출', en: 'Extracting' }, ocr: { ko: '로컬 OCR', en: 'Local OCR' }, translate: { ko: '안전하게 번역', en: 'Translating safely' }, reflow: { ko: '서식 재배치', en: 'Reflowing' }, save: { ko: '새 파일 저장', en: 'Saving copy' }, validate: { ko: '결과 다시 열어 검증', en: 'Validating output' }, completed: { ko: '완료', en: 'Completed' } };

export function DocumentWorkspace({ locale,recovery,onRecoveryConsumed,active=true }: { locale: 'ko' | 'en';recovery?:PreparedDocumentRecovery;onRecoveryConsumed?:()=>void;active?:boolean }) {
  const ko = locale === 'ko'; const [options, setOptions] = useState(defaults); const [chosen, setChosen] = useState<ChosenDocument>();
  const [secret,setSecret]=useSecretMode();
  const [busy, setBusy] = useState(false); const [jobId, setJobId] = useState<string>(); const [progress, setProgress] = useState<DocumentProgress>(); const [report, setReport] = useState<Report>(); const [error, setError] = useState<string>();
  const [settings, setSettings] = useState<AppSettings>();
  const [preview,setPreview]=useState<DocumentResultPreview>();const [previewBusy,setPreviewBusy]=useState(false);const [previewError,setPreviewError]=useState<string>();const previewRef=useRef<HTMLElement>(null);
  useEffect(()=>{if(preview||previewError){previewRef.current?.scrollIntoView({behavior:'smooth',block:'center'});previewRef.current?.focus();}},[preview,previewError]);
  useEffect(() => { void invoke<AppSettings>('get_settings').then(setSettings).catch(() => undefined); }, []);
  useEffect(()=>{setOptions((current)=>({...current,secret}));},[secret]);
  useEffect(()=>{if(!recovery)return;setOptions(recovery.options);setSecret(recovery.options.secret);void inspectDocumentPath(recovery.sourcePath,recovery.options).then(setChosen).catch((reason)=>setError(String(reason)));},[recovery,setSecret]);
  useEffect(() => { let disposed=false; let stop: undefined|(()=>void); void getCurrentWebview().onDragDropEvent((event) => { if (active && !disposed && event.payload.type === 'drop') { const path=event.payload.paths.find((value) => /\.(docx|pptx|xlsx|pdf)$/i.test(value)); if (path) void inspectDocumentPath(path,options).then((value)=>{setChosen(value);setReport(undefined);setError(undefined);}).catch((reason)=>setError(String(reason))); } }).then((unlisten)=>{if(disposed)unlisten();else stop=unlisten;});return()=>{disposed=true;stop?.();};},[active,options]);
  useEffect(() => { let disposed = false; let stop: undefined | (() => void); void listen<DocumentJobEvent>('document-job', (event) => { const payload=event.payload;if(jobId&&payload.jobId!==jobId)return;if(payload.type==='progress'){setProgress({jobId:payload.jobId,stage:payload.checkpoint.stage,unitId:payload.checkpoint.stableUnitId,completed:payload.checkpoint.completed,total:payload.checkpoint.total});}else if(payload.type==='completed'){setReport(payload.report);}else if(payload.type==='failed'){setError(payload.code);} }).then((unlisten) => { if (disposed) unlisten(); else stop = unlisten; }); return () => { disposed = true; stop?.(); }; }, [jobId]);
  const percent = useMemo(() => progress?.stage === 'inspect' ? 5 : progress?.stage === 'validate' ? 94 : progress ? 12 + Math.round(74 * progress.completed / Math.max(1, progress.total)) : 0, [progress]);
  const choose = async () => { setError(undefined); setReport(undefined); try { const value = await chooseDocument(options); if (value) setChosen(value); } catch (reason) { setError(String(reason)); } };
  const start = async () => { if (!chosen) return; const id = crypto.randomUUID(); setJobId(id); setBusy(true); setProgress({ jobId: id, stage: 'inspect', completed: 0, total: 1 }); setError(undefined); setReport(undefined); try { setReport(await translateDocument(id, chosen.sourcePath, options,recovery?{recordId:recovery.recordId,optionHash:recovery.optionHash}:null));onRecoveryConsumed?.(); } catch (reason) { setError(String(reason)); } finally { setBusy(false); } };
  const cancel = async () => { if (jobId) await cancelDocumentTranslation(jobId); };
  const navigateLocation=async(location:string)=>{if(!report)return;setPreviewBusy(true);setPreviewError(undefined);try{setPreview(await getDocumentResultPreview(report.outputPath,location));}catch{setPreview(undefined);setPreviewError(ko?'이 위치는 결과 미리보기를 만들 수 없습니다. 보고 항목에서 확인하세요.':'A result preview is unavailable for this location. Review the report item instead.');}finally{setPreviewBusy(false);}};
  const formatSummary = chosen?.manifest.format === 'pdf' ? `${chosen.manifest.pageCount} ${ko ? '페이지' : 'pages'} · ${chosen.manifest.pageKinds.filter((v) => v === 'scanned').length} OCR` : `${chosen?.manifest.segmentCount ?? 0} ${ko ? '개 텍스트 영역' : 'text segments'}`;
  return <section className="document-workspace" aria-labelledby="document-title">
    <h2 id="document-title">{ko ? '서식 유지 문서 번역' : 'Format-preserving document translation'}</h2>
    <p>{ko ? 'DOCX, PPTX, XLSX, PDF를 검사하고 원본을 건드리지 않은 새 번역 파일을 만듭니다.' : 'Inspect DOCX, PPTX, XLSX and PDF, then create a translated copy without changing the original.'}</p>
    <SecretModeSwitch locale={locale} value={secret} onChange={setSecret}/>
    {secret&&<p className="document-risk" role="status">{ko?'시크릿 문서 작업은 앱을 다시 시작한 뒤 복구할 수 없습니다.':'Secret document jobs cannot be recovered after restarting the app.'}</p>}
    <div className="document-picker" aria-label={ko ? '문서를 끌어 놓거나 선택하세요' : 'Drop or choose a document'}><button type="button" className="primary-action" onClick={() => void choose()} disabled={busy}>{ko ? '문서 선택' : 'Choose document'}</button>{chosen && <div role="status"><strong>{chosen.manifest.fileName}</strong><span className="format-badge">{chosen.manifest.format.toUpperCase()}</span><span>{formatSummary}</span>{chosen.manifest.hasSignatures && <span className="document-risk">{ko ? '전자서명 있음' : 'Contains signatures'}</span>}</div>}</div>
    <DocumentOptions locale={locale} value={options} format={chosen?.manifest.format} disabled={busy} profiles={settings?.profiles.map(({id,name})=>({id,name})) ?? []} savedModel={settings?.selectedModel.type === 'specific' ? settings.selectedModel.id : undefined} onChange={setOptions}/>
    <div className="document-actions"><button type="button" className="primary-action" disabled={!chosen || busy} onClick={() => void start()}>{ko ? '새 번역 파일 만들기' : 'Create translated copy'}</button>{busy && <button type="button" onClick={() => void cancel()}>{ko ? '취소' : 'Cancel'}</button>}</div>
    {busy && <div className="document-progress" role="status" aria-live="polite"><progress max="100" value={percent}/><span>{stages[progress?.stage ?? 'inspect']?.[ko ? 'ko' : 'en']} · {percent}%</span><small>{ko ? '문서 내용과 전체 경로는 진행 기록에 포함되지 않습니다.' : 'Document content and full paths are excluded from progress records.'}</small></div>}
    {error && <div role="alert" className="document-error"><p>{ko ? `문서 번역 실패: ${error}` : `Document translation failed: ${error}`}</p><button type="button" onClick={() => void start()} disabled={!chosen || busy}>{ko ? '다시 시도' : 'Retry'}</button></div>}
    {report&&(previewBusy||preview||previewError)&&<section ref={previewRef} tabIndex={-1} className="document-result-preview" aria-label={ko?'결과 문서 위치 미리보기':'Result document location preview'}><h3>{ko?'결과 위치 미리보기':'Result location preview'}</h3>{previewBusy&&<p role="status">{ko?'결과 파일에서 위치를 읽는 중입니다.':'Reading the location from the result file.'}</p>}{previewError&&<p role="alert">{previewError}</p>}{preview?.kind==='pdfPage'&&<figure><img src={preview.imageDataUrl} width={preview.width} height={preview.height} alt={ko?`${preview.label} 번역 결과`:`Translated result ${preview.label}`}/><figcaption>{preview.label}</figcaption></figure>}{preview?.kind==='pptxSlide'&&<><strong>{preview.label}</strong><div className="document-slide-preview" style={{aspectRatio:`${Math.max(1,preview.width)} / ${Math.max(1,preview.height)}`}}>{preview.shapes.map((shape,index)=>{const focused=preview.focusTextOrdinal!==undefined&&shape.textStart<=preview.focusTextOrdinal&&preview.focusTextOrdinal<shape.textEnd;return <div key={`${shape.id}-${index}`} className={focused?'focused':''} style={{left:`${100*shape.x/Math.max(1,preview.width)}%`,top:`${100*shape.y/Math.max(1,preview.height)}%`,width:`${100*shape.width/Math.max(1,preview.width)}%`,height:`${100*shape.height/Math.max(1,preview.height)}%`}} title={shape.name}>{shape.text}</div>})}</div></>}{preview?.kind==='xlsxCell'&&<table className="document-grid-preview"><thead><tr><th></th>{preview.columns.map(column=><th key={column}>{column}</th>)}</tr></thead><tbody>{preview.rows.map((row,index)=><tr key={index}><th>{row[0]?.reference.replace(/^[A-Z]+/,'')}</th>{row.map(cell=><td key={cell.reference} className={cell.focused?'focused':''}>{cell.value}</td>)}</tr>)}</tbody></table>}{preview?.kind==='docxContext'&&<><strong>{preview.label}</strong><ol className="document-context-preview">{preview.lines.map(line=><li key={line.ordinal} className={line.focused?'focused':''}>{line.text}</li>)}</ol></>}</section>}
    {report && <DocumentReport locale={locale} report={report} onRetry={() => void start()} onNavigateLocation={(location)=>void navigateLocation(location)}/>}</section>;
}
